### ISSUE TITLE
How to make data file

### ISSUE THREAD

**Issue by nitishkumarmishra** [moshi4/pycirclize-data#1]
Hi,
I want to use pycirclize-data for 'mm39'. Can you please upload the dataset for 'mm39' or suggest an idea to create these files-

mm39_chr.bed]
mm39_cytoband.tsv
mm39_genomic_link.tsv

Thanks
Nitish

**Comment by moshi4** [comment]
Hi @nitishkumarmishra,

Chromosome BED files for mm10 and mm39 can be obtained from https://genome.ucsc.edu/cgi-bin/hgTables.
I could not find any cytoband or genomic_link data for mm39, so I cannot provide them.

[mm39_chr.zip](https://github.com/moshi4/pycirclize-data/files/11414769/mm39_chr.zip)

___

With pyCirclize, `mm39_chr.bed` can be visualized as follows.

```python
from pycirclize import Circos
from pycirclize.utils import ColorCycler

# Initialize Circos from BED chromosomes
circos = Circos.initialize_from_bed("mm39_chr.bed", space=3)
circos.text("Mus musculus (mm39)", size=15)

# Plot chromosomes
ColorCycler.set_cmap("gist_rainbow")
colors = ColorCycler.get_color_list(len(circos.sectors))
for sector, color in zip(circos.sectors, colors):
    sector.text(sector.name, size=10)
    chr_track = sector.add_track((95, 100))
    chr_track.axis(fc=color)

circos.savefig("mm39_chr.png")
```

**mm39_chr.png**

![mm39_chr](https://user-images.githubusercontent.com/41852815/236672322-82c6e354-911a-48d7-ba89-0243cf9e8b75.png)
