### ISSUE TITLE
How to open or import my file from local disk?

### ISSUE THREAD

**Issue by Zymeth0211** [moshi4/pycirclize-data#2]
Dear mr. Moshi4 and team

I am really interested and appreciate with your valuable circos system.

I would like to ask how to import my file from a local disk. Unlike PyCircos which used 'with' function. In your case, you use your repository and perform 'import' and 'from'. But how about local file, could you show me the way?
and yes, I have data in csv format, but is it necessary to change it to .bed format for making circle?

Another question is I would like to know code for available colors in your pycirclize, if I may?

Thank you in advance
Best regards,

**Comment by moshi4** [comment]
Hi @Zymeth0211,

> I would like to ask how to import my file from a local disk. Unlike PyCircos which used 'with' function. In your case, you use your repository and perform 'import' and 'from'. But how about local file, could you show me the way?

I don't understand this question at all. Perhaps there is some fundamental misunderstanding.
Functions to get example files, such as pyCirclize's `load_eukaryote_example_dataset()`, download the file locally and return the local file path. You can check it with the following code.

```python
from pycirclize.utils import load_eukaryote_example_dataset

chr_bed_file = load_eukaryote_example_dataset("hg38")[0]

# Print chromosome bed local file path
print(chr_bed_file)

# Print chromosome bed local file content
with open(chr_bed_file) as f:
    print(f.read())
```

> I have data in csv format, but is it necessary to change it to .bed format for making circle?

I think you just need to create a dict of the sector name and size from your CSV file.

```python
from pycirclize import Circos
from pycirclize.utils import ColorCycler

# Sector name & size dict
sectors = dict(chr1=248956422, chr2=242193529, chr3=198295559, chr4=190214555)

circos = Circos(sectors, space=5)

ColorCycler.set_cmap("Set3")
for sector in circos.sectors:
    sector.text(sector.name)
    track = sector.add_track((95, 100))
    track.axis(fc=ColorCycler())

circos.savefig("example.png")
```

![example](https://github.com/moshi4/pycirclize-data/assets/41852815/aa109b68-a400-41e3-8c12-743a666bd498)

> I would like to know code for available colors in your pycirclize, if I may?

Since pyCirclize is a matplotlib based library, you can use all the [color codes](https://matplotlib.org/stable/gallery/color/named_colors.html) and [colormaps](https://matplotlib.org/stable/users/explain/colors/colormaps.html) in matplotlib.

**Comment by Zymeth0211** [comment]
Thank you for your reply.

I am sorry. I have just been learning basic Python for a couple of weeks. So, I might need clarification in terms of fundamentals. As an example from your code about 'def load_example_image_file', if I use this code, it will take an available photo, such as a Python logo. After I downloaded your sample data to my file and added my photo in .png format, I could not take my photo for the output.


```
def load_example_image_file(filename: str) -> Path:
    """Load example image file from local package data

    e.g. `python_logo.png`

    Parameters
    ----------
    filename : str
        Image file name

    Returns
    -------
    image_file_path : Path
        Image file path
    """
    image_dir = Path(__file__).parent / "example_data" / "images"
    image_filenames = [f.name for f in image_dir.glob("*.png")]

    if filename.lower() in image_filenames:
        return image_dir / filename.lower()
    else:
        err_msg = f"{filename=} is not found.\n"
        err_msg += f"Available filenames = {image_filenames}"
        raise FileNotFoundError(err_msg)
``` 

Then I executed it.
```
from pycirclize import Circos
from pycirclize.utils import load_example_image_file

sectors = {"A": 10, "B": 15, "C": 12, "D": 20, "E": 15}
circos = Circos(sectors, space=5)
for sector in circos.sectors:
    # Plot line in sector region
    sector.axis(ec="grey")
    for r in range(10, 100, 10):
        sector.line(r=r, ec="lightgrey")
    # Plot raster image (python logo)
    logo_file = load_example_image_file("random.png")
    sector.raster(logo_file, r=110, label=sector.name)
    sector.raster(logo_file, r=50, size=0.1, rotation="auto", border_width=5)
    sector.text(sector.name, r=62)

fig = circos.plotfig()
``` 

and error message
FileNotFoundError: filename='random.png' is not found.
Available filenames = ['python_logo.png']

So, my question is how to upload or import my picture to load_example_image_file to become  Available filenames = ['python_logo.png', 'random.png']

Once again, thank you for your help.
and happy holiday!

**Comment by moshi4** [comment]
`load_example_image_file()` is a function to retrieve an example image file provided by pyCirclize. Users who already have an image file do not need to use that function.

```diff
from pycirclize import Circos
from pycirclize.utils import load_example_image_file

sectors = {"A": 10, "B": 15, "C": 12, "D": 20, "E": 15}
circos = Circos(sectors, space=5)
for sector in circos.sectors:
    # Plot line in sector region
    sector.axis(ec="grey")
    for r in range(10, 100, 10):
        sector.line(r=r, ec="lightgrey")
    # Plot raster image (python logo)
-   logo_file = load_example_image_file("random.png")
+   logo_file = "random.png"
    sector.raster(logo_file, r=110, label=sector.name)
    sector.raster(logo_file, r=50, size=0.1, rotation="auto", border_width=5)
    sector.text(sector.name, r=62)

fig = circos.plotfig()
```
